<?php

declare(strict_types=1);

namespace Ecurring\WooEcurring\Subscription\Mandate;

use DateTime;

/**
 * Entity that represents an eCurring mandate.
 */
interface SubscriptionMandateInterface
{
    /**
     * Return mandate code.
     *
     * This is the unique string generated by eCurring when subscription was created.
     *
     * @return string
     */
    public function getMandateCode(): string;

    /**
     * Whether this mandate was accepted.
     *
     * @return bool
     */
    public function getAccepted(): bool;

    /**
     * Return date and time when this mandate was accepted or null if it wasn't.
     *
     * @return DateTime|null
     */
    public function getAcceptedDate(): ?DateTime;

    /**
     * A link to the page where mandate can be accepted.
     *
     * @return string Subscription activation page uri.
     */
    public function getConfirmationPageUrl(): string;

    /**
     * Whether the confirmation page URI was sent to the customer.
     *
     * @return bool
     */
    public function getConfirmationSent(): bool;
}
